### PR TITLE
Naming changes + test tidying

### PR DESCRIPTION
**Pull request by robotdevil**
Rename the Resolver class to ResolverMap to reflect the fact it is a collection of resolvers rather than a single resolver. Hopefully it will remove the confusion between our concept of a resolver and GraphQL's.

Renamed ConnectorWithIdentity and IdentityConfig to ResourceWithIdConnector and ResourceWithIdBatchFetcher to try and make it easier to intuit what they are for. 

Updated the docs with a bit more information about the three elements to use when building GraphQL APIs in bright-js-framework.

The new names are a suggested starting point - if anyone has any better suggestions that still maintain an accurate description of the classes and their purpose let me know before merging.

Also, moved repeated paths and filenames from the GraphQL server test into constants to avoid repetition.

### CODE REVIEW

**Comment by lloydnye** [comment]
Looks good to me, more descriptive names are always good :+1:

**Review by lloydnye — DISMISSED** [review]

**Comment by chrisdevereux** [comment]
Would suggest waiting until the plugin loading fixes are merged and rebasing onto that as it will probably be easier to merge that way around (and it supersedes the changes to the test files)

**Comment by chrisdevereux** [comment]
How about IdentityConnector -> ResourceConnector and IdentityConfig -> ResourceBatchFetcher?

**Comment by robotdevil** [comment]
ResourceConnector sounds fine to me (assuming the fact that the Resource has an ID isn't integral - it sounded like it was in the comment above the class). 

I think Resource suffers from the same problem as IdentityConfig in that it doesn't convey any information about what the thing is or why you are building one to pass to the connector. It also might create confusion when it comes to implementations of ResourceConnectors... 'ResourceConnector' is to 'Resource' as 'AssetConnector' is to 'Asset'? Doesn't seem right?

Maybe I've misunderstood the comment at the top of the IdentityConfig object? Is it purely a implementation of getting many Resources?

**Comment by chrisdevereux** [comment]
Also suggest GraphQLType instead of ResolverMap? Think it's a bit more intuitive to name it by its function rather than its structure.

**Comment by robotdevil** [comment]
I agree - I wasn't too keen on the 'Map' part to be honest, I don't like exposing the underlying implementation - GraphQLResolvers? ResolverLibrary?

**Comment by chrisdevereux** [comment]
SchemaType? Makes it clear that it corresponds to a type in the schema.

**Comment by robotdevil** [comment]
Assuming that a 'Type' in GraphQL terms is something with a collection of Resolvers then yep - sounds good to me...

**Review by chrisdevereux — APPROVED** [review]

**Pull request merged**
