### PR TITLE
Breaking: Add imperative API to set query variables on a GraphQL query

### PR DESCRIPTION
**Pull request by chrisdevereux**
This replaces the previous API, which implicitly inherited query variables from the react
component

This is:
   * Better for typesafety
   * More obvious (it wans't always clear where query variables were coming from before)
   * Works in environments where there aren't any component props (eg. plugins)
   * Removes need to 'nest' components unnecessarily (eg. if a query depends on state, rather than props of a parent component)

Component which provide variables to a query will need to be updated. They should use the new API to set query variables in `componentWillMount`

### CODE REVIEW

**Comment by Cowbacca** [comment]
So now if the props of a React component change, the query variables will not be automatically updated right?  If you want this behaviour, do you have to set it up manually in componentWillRecieveProps?

**Comment by chrisdevereux** [comment]
That's right. Although I'd argue that this wouldn't be too surprising as the props aren't picked up automatically in the first place anyway.

We could potentially also add a helper component for cases where more implicit behaviour is desirable. You could imagine the API looking something like this:

````
<GraphQLData query={GetUserQuery} variables={{ id: this.props.userId }}>
{
  ({ data: { name } }) => <div>username: {name}</div>
}
</GraphQLData>
````

This would keep things reactive while making it clear where props are coming from. Might be worth it if we find it difficult to keep query variables in sync.

**Comment by Cowbacca** [comment]
I was thinking something more along the lines of an optional function from props (possibly state too if there's a hook for that) to query variables that could be passed to the decorator, which would then be used to update the query variables whenever the props changed.

We can obviously just add this kind of thing in as soon as we need it though, no need to do anything now.

**Review by Cowbacca — APPROVED** [review]

**Comment by chrisdevereux** [comment]
The problem with allowing state to be passed in is that query results are state, so you'd have to think very carefully about how to avoid infinitely cascading refetches caused by state changing due to a query completing.

This sidesteps that issue by making everything explicit, then maybe layering a helper API on top if needed.

**Review by robotdevil — APPROVED** [review]

**Pull request merged**
